name: Build and Deploy to Firebase Hosting
on:
  push:
    branches:
      - master  # or your default branch name like 'master'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install  # or use 'yarn' if you prefer

    - name: Build
      run: npm run build  # or your build command here

    - name: Deploy to Firebase
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
